### ISSUE TITLE
Issue installing `cargo-generate` on arm64 macos

### ISSUE THREAD

**Issue by gbj** [akesson/cargo-leptos#11]
When I tried to run `cargo leptos new --name example` for the first time it gave me the error

`Error: Unable to download cargo-generate for macos x86_64 due to: failed to download from https://github.com/cargo-generate/cargo-generate/releases/download/0.17.3/cargo-generate-0.17.3-x86_64-apple-darwin.tar.gz`

I'm on arm64 macos. I was able to install `cargo-generate` manually using `cargo install cargo-generate`

**Comment by gbj** [comment]
Same applies to sass: I get

```
Error: compile sass/scss: style/main.scss

Caused by:
    0: Try manually installing sass: https://sass-lang.com/install
    1: Unable to download sass for macos x86_64 due to: failed to extract tarball from https://github.com/sass/dart-sass/releases/download/1.56.1/dart-sass-1.56.1-macos-x64.tar.gz
```

**Comment by akesson** [comment]
I don't have an idea. The [code for detecting](https://github.com/akesson/cargo-leptos/blob/c2f04b0b1770cfd7f060df82d1e0f9694a6dd79d/src/util.rs#L129) the os is:
```rust
let target_arch = if cfg!(target_arch = "x86_64") {
        "x86_64"
    } else if cfg!(target_arch = "aarch64") {
        "aarch64"
    } else {
        bail!("unsupported target architecture")
    };
```
And for `cargo-generate` it is used [here](https://github.com/akesson/cargo-leptos/blob/c2f04b0b1770cfd7f060df82d1e0f9694a6dd79d/src/run/new.rs#L105)

Would be great if you could investigate, as I can't reproduce it on my own M1.

**Comment by gbj** [comment]
Oh man. Apparently I have had Rust set up using `nightly-x86_64-apple-darwin` for the last year while running it on an M1. What a self-own.
