### ISSUE TITLE
Impossible to compile on fresh git clone

### ISSUE THREAD

**Issue by Kaporos** [akesson/cargo-leptos#29]
The compiler leaves me this message:

   Compiling cargo-leptos v0.0.8 (C:\Users\Theo\Workspace\cargo-leptos)
error[E0063]: missing fields filter and map in initializer of ExtractOpts
   --> src\ext\exe.rs:113:18
    |
113 |                 &decompress::ExtractOpts { strip: 1 },
    |                  ^^^^^^^^^^^^^^^^^^^^^^^ missing `filter` and `map`

For more information about this error, try `rustc --explain E0063`.
error: could not compile cargo-leptos due to previous error
error: failed to compile cargo-leptos v0.0.8 (C:\Users\Theo\Workspace\cargo-leptos), intermediate artifacts can be found at

Cargo version: cargo 1.68.0-nightly (70898e522 2022-12-05)

**Comment by Kaporos** [comment]
Update: My bad, i ran cargo update

**Comment by akesson** [comment]
It would be great if you could test it on the latest beta:
`cargo install cargo-leptos --branch beta --git https://github.com/akesson/cargo-leptos cargo-leptos`

For more info see the Discord: https://discord.gg/YdRAhS7eQB

**Comment by akesson** [comment]
Closing due to no reply from the reporter.
