### ISSUE TITLE
cargo-leptos can't find sass binaries

### ISSUE THREAD

**Issue by msmaiaa** [akesson/cargo-leptos#32]
I am using Windows 10 with rust nightly and this problem occurs with a fresh project created using "cargo leptos new --git https://github.com/leptos-rs/start"

![error](https://i.imgur.com/YqqYLrr.png)

I think it happens because the extracted content actually has a "dart-sass" folder instead of the sass binaries:
![folder](https://i.imgur.com/IwDCFcC.png)
The build process runs just fine if i move the files from the "dart-sass" folder to the sass folder
![folder2](https://i.imgur.com/T53taLz.png)

The same problem also occurs with "wasm-opt-version_111" when building the project

**Comment by msmaiaa** [comment]
The same problem also occurs with "wasm-opt-version_111" when building the project

**Comment by akesson** [comment]
I've been able to reproduce and fix the issues using github test actions on windows. The latest 0.1.0 release has the fixes.
