### ISSUE TITLE
cargo leptos serve failes: Could not create "/pkg/pkg" 

### ISSUE THREAD

**Issue by joepio** [akesson/cargo-leptos#36]
- `cargo leptos new -g https://github.com/leptos-rs/start`
- `cargo leptos watch`

```
Cargo finished cargo build --package=leptos-start --bin=leptos-start --target-dir=target/server --no-default-features --features=ssr
Error: at `/Users/joep/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-leptos-0.1.0/src/command/serve.rs:8:42`

Caused by:
    0: Could not create "/pkg/pkg" at `/Users/joep/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-leptos-0.1.0/src/ext/fs.rs:58:10`
    1: Read-only file system (os error 30)
```

- cargo-leptos 0.1.0
- rustc 1.67.0-nightly (85f4f41de 2022-11-08)
- MacOS 13.1, m1 pro

**Comment by gbj** [comment]
This may be due to my own misunderstanding... the template has, among its `[package.metadata.leptos]` settings, the following:
```
site-root = "/pkg"
site-pkg-dir = "pkg" 	
```
It's possible I'm misunderstanding these settings (I think I just borrowed them from Ben's examples) or that there's something wrong in my setup or in the integration.

**Comment by akesson** [comment]
The `site-root` should be a relative path. It defaults to `target/site` in order to have all built artifacts in the same place, but if you want it outside of the target dir, then maybe just `site`?

**Comment by gbj** [comment]
Thanks — sounds like this is actually an issue with the new integration. I'll revert to using your Actix integration for now, and bring it up w/ Ben. Thanks.

**Comment by benwis** [comment]
Yeah, that is not the right way to do things. Basically site-root should be `server/target` if you're using cargo-leptos and `pkg` if you're using wasm-pack. The latest PR for leptos supports that approach.

**Comment by gbj** [comment]
My bad! I'm going to migrate the leptos starter example today or tomorrow, so feel free to close this issue any time.
