### ISSUE TITLE
[feature] add option to build client files first

### ISSUE THREAD

**Issue by beeb** [akesson/cargo-leptos#47]
It seems `cargo-leptos` (which is amazing btw!) builds the server and client files in parallal. While this is generally desired for speed, I would like in my project to bundle the js, wasm and css files directly into the binary with [`rust-embed`](https://crates.io/crates/rust-embed) which requires that the files exist when the server binary is compiled.

Would it be possible to add an option to force the client assets to be finished writing before the server is allowed to compile?

Thanks a bunch

**Comment by akesson** [comment]
Hey @beeb. Only `cargo leptos watch` builds in parallel. Try using `cargo leptos build`

**Comment by beeb** [comment]
That's what I did actually, and the rust-embed was complaining that the files didn't exist. When copying the assets to a different directory, all worked as expected.

**Comment by akesson** [comment]
Try using `cargo-leptos` from branch [issue-47](https://github.com/akesson/cargo-leptos/tree/issue-47). I changed so that the server part is built last (instead of first as it was before)

**Comment by beeb** [comment]
![image](https://user-images.githubusercontent.com/703631/212128447-ccab370a-1247-4b6f-960c-f05d2f367940.png)

I get the same result unfortunately. Maybe I did something wrong when installing the branch version?

**Comment by beeb** [comment]
It works! Thanks a lot, that was super fast :)

**Comment by beeb** [comment]
I spoke a bit too soon, works for `js` and `css` but not `wasm`

**Comment by beeb** [comment]
Yep, it's not a bug with cargo-leptos, can be closed! Thanks again

**Comment by akesson** [comment]
Enjoy Leptos :)
